#!/usr/bin/env python3
"""Generate docs/javascripts/builder-data.js from the mc-tui data tables.

bin/lib/data.fish is the single source of truth for the command catalog, the
item list and the picker tables (with their official pt-BR names). This
extracts those pipe-delimited blocks and emits them as JSON for the web command
builder (docs/builder.md). Run via `mise run builder-data` (the site task
depends on it); the output file is generated, not committed.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = (ROOT / "bin" / "lib" / "data.fish").read_text()
OUT = ROOT / "docs" / "javascripts" / "builder-data.js"


def table(name: str) -> list[list[str]]:
    """Rows of the first echo'…' block inside `function <name>`."""
    m = re.search(rf"function {name}\b.*?echo '(.*?)'", SRC, re.S)
    if not m:
        raise SystemExit(f"builder-data: table not found in bin/lib/data.fish: {name}")
    return [line.split("|") for line in m.group(1).split("\n")]


data = {
    "catalog": [{"c": c, "t": t, "d": d} for c, t, d in table("catalog")],
    "items": [
        {"g": g, "id": i, "pt": pt, "n": n} for g, i, pt, n in table("items")
    ],
}
for tbl in ("enchantments", "effects", "entities", "structures", "biomes"):
    data[tbl] = [{"id": i, "n": n} for i, n in table(f"data_{tbl}")]

OUT.write_text(
    "// Generated by scripts/builder-data.py from bin/lib/data.fish — do not edit.\n"
    f"window.MC_DATA = {json.dumps(data, ensure_ascii=False, separators=(',', ':'))};\n"
)
counts = ", ".join(f"{k}: {len(v)}" for k, v in data.items())
print(f"builder-data: wrote {OUT.relative_to(ROOT)} ({counts})")
